name: Format

on:
    pull_request:
        paths:
            - '**.css'
            - '**.js'
            - '**.ts'
            - '**.vue'

jobs:
    eslint:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                restore-keys: ${{ runner.os }}-node-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn global add node-gyp && yarn install --frozen-lockfile

            - name: Run eslint
              run: yarn lint:fix

            - uses: stefanzweifel/git-auto-commit-action@v4.1.0
              with:
                  commit_message: "style: resolve style guide violations"
                  branch: ${{ github.head_ref }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
